version: '3'
services:
  web:
    build: .
    command: node app.js
    ports:
      - "8080:8080"
    environment:
        PORT: 8080
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
